docker:
  image: "g4s8/rultor-android"
env:
  ANDROID_SDK_ROOT: /opt/android
decrypt:
  settings.xml: "repo/settings.xml.asc"
  pubring.gpg: "repo/pubring.gpg.asc"
  secring.gpg: "repo/secring.gpg.asc"
release:
  script: |
    git commit --allow-empty -am "${tag}"
    ./gradlew -PnewVersion="${tag}" eoandroidconcurrency:clean
    ./gradlew -PnewVersion="${tag}" eoandroidconcurrency:assemble
    ./gradlew -PnewVersion="${tag}" eoandroidconcurrency:publishReleasePublicationToSonatypeRepository
    ./gradlew -PnewVersion="${tag}" eorest:clean
    ./gradlew -PnewVersion="${tag}" eorest:jar
    ./gradlew -PnewVersion="${tag}" eorest:publishReleasePublicationToSonatypeRepository
    ./gradlew closeAndReleaseRepository
