docker:
  image: "coala/rultor-python"
  as_root: true
architect:
  - RoRoche
install:
  - "pip3 install requests"
decrypt:
  bitrise.txt: "repo/secrets/bitrise.txt.asc"
release:
  script: |
    git commit --allow-empty -am "${tag}"
    TOKEN=$(cat /home/r/bitrise.txt)
    python3 repo/scripts/startBitriseBuild.py --token ${TOKEN} --appSlug 4b269ce2e4a54a10 --workflowId deploy --gitTag ${tag}
